author=xiaochun
name=ZrLog \u9ED8\u8BA4\u4E3B\u9898
url=https://blog.zrlog.com
digest=\u8F7B\u91CF\u3001\u54CD\u5E94\u5F0F\uFF0C\u652F\u6301\u6DF1\u8272\u6A21\u5F0F
version=1.0
previewImages=images/preview-1.0.webp
staticResource=css/,js/
